import React, { Component, PropTypes } from 'react';
import sematable, { Table } from 'sematable';
import CheckboxVisitCont from '../containers/communityUI/CheckboxVisitCont';
import CheckboxComplCont from '../containers/communityUI/CheckboxComplCont';
import EditCommunCont from '../containers/communityUI/EditCommunCont';
import LinkToHouseholdCont from '../containers/communityUI/LinkToHouseholdCont';
import RemarksCont from '../containers/communityUI/RemarksCont';

const columns = [
  {
    key: 'id',
    header: 'Household ID',
    sortable: false,
    searchable: false,
    primaryKey: true,
    hidden: true
  }, // Hidden ID key - generated by addHousehold
  {
    key: 'name',
    header: 'Household Name',
    sortable: true,
    searchable: true,
    primaryKey: false,
    Component: LinkToHouseholdCont
  }, // clickable - link to Houshold
  {
    key: 'householdNumber',
    header: 'Household #',
    sortable: true,
    searchable: true,
    primaryKey: false
  }, // Prop (text)
  {
    key: 'address',
    header: 'Address',
    sortable: false,
    searchable: false,
    primaryKey: false
  }, //Prop (text)
  {
    key: 'visited',
    header: 'Visited',
    sortable: true,
    searchable: false,
    primaryKey: false,
    Component: CheckboxVisitCont
  }, // State (Checkbox)
  {
    key: 'visitDate',
    header: 'Date visited',
    sortable: false,
    searchable: false,
    primaryKey: false
  }, // Prop - from Visited
  {
    key: 'completed',
    header: 'Completed',
    sortable: true,
    searchable: false,
    primaryKey: false,
    Component: CheckboxComplCont
  }, // Prop - calculated from HouseholdUI
  {
    key: 'remarks',
    header: 'Remarks',
    sortable: false,
    searchable: false,
    primaryKey: false,
    Component: RemarksCont
  }, // State - Add Remarks
  {
    key: 'edit',
    header: '',
    Component: EditCommunCont
  } // State - Edit household
];

/**
 * Component for Community Table
 */
class Community extends Component {
  render() {
    const { handleClick, form, attributes } = this.props;
    return (
      <div>
        <Table {...this.props} columns={columns} />
        <button
          type="button"
          className="btn btn-default"
          onClick={handleClick}
          {...attributes}
        >
          Add Household
        </button>
        {form && form()}
      </div>
    );
  }
}

/**
 * @prop {object} propTypes
 * @prop {object} propTypes.headers - headers of columns 
 * @prop {object[]} propTypes.data - state
 * @prop {string} propTypes.primaryKey - defines what column that should be primary key
 * @prop {attrbutes} propTypes.attributes - attributes for 'Add Household' button
 * @prop {form} propTypes.form - 'Add Household Registration' form
 * @prop {function} propTypes.handleClick - dispatch function
 */
Community.propTypes = {
  headers: PropTypes.object.isRequired,
  data: PropTypes.array.isRequired,
  primaryKey: PropTypes.string.isRequired,
  attributes: PropTypes.object.isRequired,
  form: PropTypes.func.isRequired,
  handleClick: PropTypes.func.isRequired
};

export default sematable('CommunityTable', Community, columns);
